import re
import uuid
import numpy as np
from typing import List, Dict, Any, Optional
from sentence_transformers import SentenceTransformer
from rank_bm25 import BM25Okapi
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct, Filter, FieldCondition, MatchValue
from app.config import settings


class HybridVectorStore:
    def __init__(self):
        # 1. Initialize Dense Embedding Encoder
        self.encoder = SentenceTransformer(settings.EMBEDDING_MODEL_NAME)
        self.embedding_dim = self.encoder.get_embedding_dimension()
        
        # 2. Initialize Embedded Local Qdrant Instance
        storage_path_str = str(settings.QDRANT_STORAGE_PATH.resolve())
        self.client = QdrantClient(path=storage_path_str)
        self.collection_name = settings.QDRANT_COLLECTION_NAME
        self._init_collection()
        
        # 3. In-Memory BM25 Sparse Corpus
        self.bm25_chunks: List[Dict[str, Any]] = []
        self.bm25_model: Optional[BM25Okapi] = None

    def _init_collection(self):
        """Creates the Qdrant collection if it does not already exist."""
        collections = [c.name for c in self.client.get_collections().collections]
        if self.collection_name not in collections:
            self.client.create_collection(
                collection_name=self.collection_name,
                vectors_config=VectorParams(size=self.embedding_dim, distance=Distance.COSINE)
            )

    def _convert_to_uuid(self, string_id: str) -> str:
        """Converts string chunk IDs into deterministic UUID strings for Qdrant compliance."""
        return str(uuid.uuid5(uuid.NAMESPACE_DNS, string_id))

    def index_chunks(self, chunks: List[Dict[str, Any]]):
        """Indexes document chunks generated by Member 1 into Qdrant & BM25."""
        if not chunks:
            print("[VectorStore] Warning: No chunks provided for indexing.")
            return

        print(f"[VectorStore] Generating dense embeddings for {len(chunks)} chunks using {settings.EMBEDDING_MODEL_NAME}...")
        texts = [c["chunk_text"] for c in chunks]
        embeddings = self.encoder.encode(texts, show_progress_bar=False, batch_size=32).tolist()

        points = []
        for chunk, emb in zip(chunks, embeddings):
            qdrant_id = self._convert_to_uuid(chunk["chunk_id"])
            
            payload = {
                "chunk_id": chunk["chunk_id"],
                "doc_id": chunk["doc_id"],
                "doc_name": chunk["doc_name"],
                "page_number": chunk["page_number"],
                "section": chunk.get("section", ""),
                "chunk_text": chunk["chunk_text"],
                "year": chunk.get("year"),
                "doc_type": chunk.get("doc_type"),
                "metadata": chunk.get("metadata", {})
            }

            points.append(PointStruct(
                id=qdrant_id,
                vector=emb,
                payload=payload
            ))

        self.client.upsert(collection_name=self.collection_name, points=points)
        print(f"[VectorStore] Indexed {len(points)} vectors into Qdrant collection '{self.collection_name}'.")

        self.bm25_chunks = chunks
        tokenized_corpus = [re.findall(r'\w+', c["chunk_text"].lower()) for c in chunks]
        self.bm25_model = BM25Okapi(tokenized_corpus)
        print(f"[VectorStore] BM25 lexical index successfully built.")

    def _build_qdrant_filter(self, metadata_filter: Optional[Dict[str, Any]]) -> Optional[Filter]:
        """Maps key-value user metadata filters into Qdrant Filter objects."""
        if not metadata_filter:
            return None

        conditions = []
        for key, value in metadata_filter.items():
            conditions.append(
                FieldCondition(key=key, match=MatchValue(value=value))
            )
        return Filter(must=conditions)

    def search(
        self,
        query: str,
        top_k: int = settings.DEFAULT_TOP_K,
        similarity_threshold: float = settings.DEFAULT_SIMILARITY_THRESHOLD,
        metadata_filter: Optional[Dict[str, Any]] = None,
        use_hybrid: bool = True
    ) -> List[Dict[str, Any]]:
        """
        Executes hybrid search (Dense Vector + BM25 Lexical) using Reciprocal Rank Fusion (RRF).
        Enforces cosine similarity thresholding and payload metadata filtering.
        """
        # 1. Dense Vector Search via Qdrant query_points
        query_vector = self.encoder.encode(query).tolist()
        q_filter = self._build_qdrant_filter(metadata_filter)

        response = self.client.query_points(
            collection_name=self.collection_name,
            query=query_vector,
            limit=top_k * 5,
            query_filter=q_filter
        )
        vector_results = response.points

        # Apply similarity threshold check to dense results
        valid_dense_hits = [res for res in vector_results if res.score >= similarity_threshold]

        # Early exit: If no dense vector hit satisfies similarity_threshold, query is out-of-domain
        if not valid_dense_hits:
            return []

        valid_chunk_ids = {res.payload["chunk_id"] for res in valid_dense_hits}
        dense_score_map = {res.payload["chunk_id"]: float(res.score) for res in valid_dense_hits}

        if not use_hybrid or not self.bm25_model:
            final_chunks = []
            for hit in valid_dense_hits[:top_k]:
                item = hit.payload.copy()
                item["similarity_score"] = round(float(hit.score), 4)
                final_chunks.append(item)
            return final_chunks

        # 2. Sparse Lexical Search via BM25
        tokenized_query = re.findall(r'\w+', query.lower())
        bm25_scores = self.bm25_model.get_scores(tokenized_query) if tokenized_query else []
        
        # 3. Reciprocal Rank Fusion (RRF)
        rrf_scores: Dict[str, float] = {}
        chunk_map: Dict[str, Dict[str, Any]] = {}
        rrf_k = 60.0

        for rank, hit in enumerate(valid_dense_hits):
            c_id = hit.payload["chunk_id"]
            rrf_scores[c_id] = rrf_scores.get(c_id, 0.0) + settings.HYBRID_DENSE_WEIGHT * (1.0 / (rrf_k + (rank + 1)))
            payload_with_score = hit.payload.copy()
            payload_with_score["similarity_score"] = round(float(hit.score), 4)
            chunk_map[c_id] = payload_with_score

        if len(bm25_scores) > 0:
            bm25_ranked_indices = np.argsort(bm25_scores)[::-1]
            bm25_rank = 1
            for idx in bm25_ranked_indices:
                score = bm25_scores[idx]
                if score <= 0:
                    break
                
                chunk = self.bm25_chunks[idx]
                c_id = chunk["chunk_id"]

                # Enforce thresholding on BM25 candidates: only fuse chunks that passed dense threshold
                if c_id not in valid_chunk_ids:
                    continue
                
                if metadata_filter:
                    match = all(
                        chunk.get(k) == v or chunk.get("metadata", {}).get(k) == v 
                        for k, v in metadata_filter.items()
                    )
                    if not match:
                        continue

                rrf_scores[c_id] = rrf_scores.get(c_id, 0.0) + settings.HYBRID_SPARSE_WEIGHT * (1.0 / (rrf_k + bm25_rank))
                if c_id not in chunk_map:
                    payload_with_score = chunk.copy()
                    payload_with_score["similarity_score"] = round(dense_score_map.get(c_id, 0.0), 4)
                    chunk_map[c_id] = payload_with_score
                
                bm25_rank += 1
                if bm25_rank > top_k * 3:
                    break

        # 4. Sort Fusion Candidates & Return Top-K
        sorted_ids = sorted(rrf_scores.keys(), key=lambda cid: rrf_scores[cid], reverse=True)
        
        results = []
        for cid in sorted_ids[:top_k]:
            res_item = chunk_map[cid]
            res_item["hybrid_rrf_score"] = round(rrf_scores[cid], 6)
            results.append(res_item)

        return results